# Generated by Django 5.1.4 on 2024-12-29 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="total_cost",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
